nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'My API description'
            version: '1.0.0'
    areas:
        default:
            path_patterns: ['^/api']
